CREATE TABLE "users" (
  "idea_rank" INT NOT NULL,
  "idea_name" VARCHAR(66) NOT NULL,
  "idea_summary" TEXT NOT NULL,
  "information_story" TEXT NOT NULL,
  "possible_information_structure" TEXT NOT NULL
);

INSERT INTO "users" ("idea_rank", "idea_name", "idea_summary", "information_story", "possible_information_structure")
VALUES
  (1, 'Food Safety Inspection mobile app', 'A mobile application that helps users understand whether the food they consume is safe and healthy. The app integrates QR code scan history, previous food safety reports, recall alerts, and company transparency data. It provides location-based notifications if a food safety issue is identified in products previously scanned by the user, and allows users to explore information about food producers, origins, ingredients, and health ratings.', 'Food safety information is currently fragmented across government recall announcements, company disclosures, news reports, and supply chain records. Consumers often only learn about food safety issues after exposure because information is difficult to access or interpret. In this system, food products are linked to digital records through QR codes. When users scan a product, the system stores a standardized identifier that connects to supply chain information, inspection records, and health ratings. The application continuously monitors trusted food safety information sources and compares new alerts with the user''s scan history. If a risk is detected, the user receives a notification explaining the issue, the affected product, and recommended actions. Over time, aggregated data enables insight into patterns of food safety risk, transparency gaps, and supply chain weaknesses, helping both consumers and regulators make more informed decisions.', 'Use a portable JSON-based structure with standardized identifiers for food products. Each product contains fields such as product_id, producer_id, origin_location, processing_steps, ingredient_list, additive_list, safety_rating, certification_records, and recall_status. The QR code encodes the product_id which allows data to be retrieved from multiple systems. Separate but linkable structures exist for producer profiles, safety inspection reports, recall alerts, and user scan history. Using consistent field naming and unique identifiers enables interoperability between regulatory databases, company systems, and consumer applications, supporting data portability and integration across platforms.');